# Generated by Django 4.1 on 2022-08-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='origim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ourcalendar.ourcalendar'),
            preserve_default=False,
        ),
    ]
