# Generated by Django 4.1.3 on 2022-11-14 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourcalendar", "0004_requestcalendarfollow_calendarfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourcalendar",
            name="name",
            field=models.CharField(default=datetime.date.today, max_length=255),
            preserve_default=False,
        ),
    ]
