# Generated by Django 4.1.3 on 2022-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourcalendar", "0005_ourcalendar_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarfollow",
            name="qnt_merge",
            field=models.IntegerField(default=0),
        ),
    ]
